server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql:///myschool?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml


#showSql
logging:
  level:
    com:
      example:
        mapper : error
